services:
  auth:
    build: ./authentication-service
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MONGO_URI=mongodb+srv://niloy:29303128@stack-over-flow.pbwd2.mongodb.net/authDB?retryWrites=true&w=majority&appName=auth-service
      - JWT_SECRET=niloy1315

  post:
    build: ./post-service
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - MONGO_URI=mongodb+srv://niloy:29303128@stack-over-flow.pbwd2.mongodb.net/postDB?retryWrites=true&w=majority&appName=post-service
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_BUCKET=code-storage
    depends_on:
      - minio
      - notification
      - auth

  notification:
    build: ./notification-service
    ports:
      - "5003:5003"
    environment:
      - PORT=5003
      - MONGO_URI=mongodb+srv://niloy:29303128@stack-over-flow.pbwd2.mongodb.net/notificationDB?retryWrites=true&w=majority&appName=notification-service
    depends_on:
      - auth

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - auth
      - post
      - notification

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  minio_data:
