services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MONGO_URI: mongodb+srv://niloy:29303128@stack-over-flow.pbwd2.mongodb.net/?retryWrites=true&w=majority&appName=stack-over-flow
      JWT_SECRET: niloy1315
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_BUCKET: code-storage
    depends_on:
      - minio

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000" # Console
      - "9001:9001" # Web UI
    command: server /data --console-address ":9001"
    volumes:
      - "D:/minio-data:/data"
